server:
  port: 7777
eureka:
  instance:
    hostname: localhost  #?????Eureka??????IP
  client:
    #register-with-eureka: false   #????true ????????????Eureka?????????????????Eureka???????????????false??
    #fetch-registry: false   #????true ???????Eureka???????????????????????????????Eureka?????????????????Eureka??????????????????????????????false??
    service-url:
      defaultZone: http://localhost:8888/eureka/,http://localhost:9999/eureka/  #???Eureka???????????????http://localhost:8761/eureka??
spring:
  application:
    name: server2